// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: complex.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Dummy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dummy) Reset() {
	*x = Dummy{}
	mi := &file_complex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dummy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dummy) ProtoMessage() {}

func (x *Dummy) ProtoReflect() protoreflect.Message {
	mi := &file_complex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dummy.ProtoReflect.Descriptor instead.
func (*Dummy) Descriptor() ([]byte, []int) {
	return file_complex_proto_rawDescGZIP(), []int{0}
}

func (x *Dummy) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Dummy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MessageComplex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DummyArray    []*Dummy               `protobuf:"bytes,1,rep,name=dummy_array,json=dummyArray,proto3" json:"dummy_array,omitempty"`
	OneDummy      *Dummy                 `protobuf:"bytes,2,opt,name=one_dummy,json=oneDummy,proto3" json:"one_dummy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageComplex) Reset() {
	*x = MessageComplex{}
	mi := &file_complex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageComplex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageComplex) ProtoMessage() {}

func (x *MessageComplex) ProtoReflect() protoreflect.Message {
	mi := &file_complex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageComplex.ProtoReflect.Descriptor instead.
func (*MessageComplex) Descriptor() ([]byte, []int) {
	return file_complex_proto_rawDescGZIP(), []int{1}
}

func (x *MessageComplex) GetDummyArray() []*Dummy {
	if x != nil {
		return x.DummyArray
	}
	return nil
}

func (x *MessageComplex) GetOneDummy() *Dummy {
	if x != nil {
		return x.OneDummy
	}
	return nil
}

var File_complex_proto protoreflect.FileDescriptor

const file_complex_proto_rawDesc = "" +
	"\n" +
	"\rcomplex.proto\x12\x0fexample.complex\"+\n" +
	"\x05Dummy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"~\n" +
	"\x0eMessageComplex\x127\n" +
	"\vdummy_array\x18\x01 \x03(\v2\x16.example.complex.DummyR\n" +
	"dummyArray\x123\n" +
	"\tone_dummy\x18\x02 \x01(\v2\x16.example.complex.DummyR\boneDummyB\x19Z\x17example.com/proto/protob\x06proto3"

var (
	file_complex_proto_rawDescOnce sync.Once
	file_complex_proto_rawDescData []byte
)

func file_complex_proto_rawDescGZIP() []byte {
	file_complex_proto_rawDescOnce.Do(func() {
		file_complex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_complex_proto_rawDesc), len(file_complex_proto_rawDesc)))
	})
	return file_complex_proto_rawDescData
}

var file_complex_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_complex_proto_goTypes = []any{
	(*Dummy)(nil),          // 0: example.complex.Dummy
	(*MessageComplex)(nil), // 1: example.complex.MessageComplex
}
var file_complex_proto_depIdxs = []int32{
	0, // 0: example.complex.MessageComplex.dummy_array:type_name -> example.complex.Dummy
	0, // 1: example.complex.MessageComplex.one_dummy:type_name -> example.complex.Dummy
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_complex_proto_init() }
func file_complex_proto_init() {
	if File_complex_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_complex_proto_rawDesc), len(file_complex_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_complex_proto_goTypes,
		DependencyIndexes: file_complex_proto_depIdxs,
		MessageInfos:      file_complex_proto_msgTypes,
	}.Build()
	File_complex_proto = out.File
	file_complex_proto_goTypes = nil
	file_complex_proto_depIdxs = nil
}
