// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: enumeration.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenderInfo int32

const (
	GenderInfo_GENDER_UNSPECIFIED GenderInfo = 0
	GenderInfo_GENDER_MALE        GenderInfo = 1
	GenderInfo_GENDER_FEMALE      GenderInfo = 2
)

// Enum value maps for GenderInfo.
var (
	GenderInfo_name = map[int32]string{
		0: "GENDER_UNSPECIFIED",
		1: "GENDER_MALE",
		2: "GENDER_FEMALE",
	}
	GenderInfo_value = map[string]int32{
		"GENDER_UNSPECIFIED": 0,
		"GENDER_MALE":        1,
		"GENDER_FEMALE":      2,
	}
)

func (x GenderInfo) Enum() *GenderInfo {
	p := new(GenderInfo)
	*p = x
	return p
}

func (x GenderInfo) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GenderInfo) Descriptor() protoreflect.EnumDescriptor {
	return file_enumeration_proto_enumTypes[0].Descriptor()
}

func (GenderInfo) Type() protoreflect.EnumType {
	return &file_enumeration_proto_enumTypes[0]
}

func (x GenderInfo) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GenderInfo.Descriptor instead.
func (GenderInfo) EnumDescriptor() ([]byte, []int) {
	return file_enumeration_proto_rawDescGZIP(), []int{0}
}

type PersonalInformation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Surname       string                 `protobuf:"bytes,2,opt,name=Surname,proto3" json:"Surname,omitempty"`
	Gender        GenderInfo             `protobuf:"varint,3,opt,name=Gender,proto3,enum=example.enumirations.GenderInfo" json:"Gender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonalInformation) Reset() {
	*x = PersonalInformation{}
	mi := &file_enumeration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonalInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalInformation) ProtoMessage() {}

func (x *PersonalInformation) ProtoReflect() protoreflect.Message {
	mi := &file_enumeration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalInformation.ProtoReflect.Descriptor instead.
func (*PersonalInformation) Descriptor() ([]byte, []int) {
	return file_enumeration_proto_rawDescGZIP(), []int{0}
}

func (x *PersonalInformation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PersonalInformation) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *PersonalInformation) GetGender() GenderInfo {
	if x != nil {
		return x.Gender
	}
	return GenderInfo_GENDER_UNSPECIFIED
}

var File_enumeration_proto protoreflect.FileDescriptor

const file_enumeration_proto_rawDesc = "" +
	"\n" +
	"\x11enumeration.proto\x12\x14example.enumirations\"}\n" +
	"\x13PersonalInformation\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x18\n" +
	"\aSurname\x18\x02 \x01(\tR\aSurname\x128\n" +
	"\x06Gender\x18\x03 \x01(\x0e2 .example.enumirations.GenderInfoR\x06Gender*H\n" +
	"\n" +
	"GenderInfo\x12\x16\n" +
	"\x12GENDER_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vGENDER_MALE\x10\x01\x12\x11\n" +
	"\rGENDER_FEMALE\x10\x02B\x19Z\x17example.com/proto/protob\x06proto3"

var (
	file_enumeration_proto_rawDescOnce sync.Once
	file_enumeration_proto_rawDescData []byte
)

func file_enumeration_proto_rawDescGZIP() []byte {
	file_enumeration_proto_rawDescOnce.Do(func() {
		file_enumeration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enumeration_proto_rawDesc), len(file_enumeration_proto_rawDesc)))
	})
	return file_enumeration_proto_rawDescData
}

var file_enumeration_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_enumeration_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_enumeration_proto_goTypes = []any{
	(GenderInfo)(0),             // 0: example.enumirations.GenderInfo
	(*PersonalInformation)(nil), // 1: example.enumirations.PersonalInformation
}
var file_enumeration_proto_depIdxs = []int32{
	0, // 0: example.enumirations.PersonalInformation.Gender:type_name -> example.enumirations.GenderInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_enumeration_proto_init() }
func file_enumeration_proto_init() {
	if File_enumeration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enumeration_proto_rawDesc), len(file_enumeration_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enumeration_proto_goTypes,
		DependencyIndexes: file_enumeration_proto_depIdxs,
		EnumInfos:         file_enumeration_proto_enumTypes,
		MessageInfos:      file_enumeration_proto_msgTypes,
	}.Build()
	File_enumeration_proto = out.File
	file_enumeration_proto_goTypes = nil
	file_enumeration_proto_depIdxs = nil
}
