// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: map.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdWrapper struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdWrapper) Reset() {
	*x = IdWrapper{}
	mi := &file_map_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdWrapper) ProtoMessage() {}

func (x *IdWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_map_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdWrapper.ProtoReflect.Descriptor instead.
func (*IdWrapper) Descriptor() ([]byte, []int) {
	return file_map_proto_rawDescGZIP(), []int{0}
}

func (x *IdWrapper) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MapExample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           map[string]*IdWrapper  `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapExample) Reset() {
	*x = MapExample{}
	mi := &file_map_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapExample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapExample) ProtoMessage() {}

func (x *MapExample) ProtoReflect() protoreflect.Message {
	mi := &file_map_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapExample.ProtoReflect.Descriptor instead.
func (*MapExample) Descriptor() ([]byte, []int) {
	return file_map_proto_rawDescGZIP(), []int{1}
}

func (x *MapExample) GetIds() map[string]*IdWrapper {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_map_proto protoreflect.FileDescriptor

const file_map_proto_rawDesc = "" +
	"\n" +
	"\tmap.proto\x12\vexample.map\"\x1b\n" +
	"\tIdWrapper\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x90\x01\n" +
	"\n" +
	"MapExample\x122\n" +
	"\x03ids\x18\x01 \x03(\v2 .example.map.MapExample.IdsEntryR\x03ids\x1aN\n" +
	"\bIdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.example.map.IdWrapperR\x05value:\x028\x01B\x19Z\x17example.com/proto/protob\x06proto3"

var (
	file_map_proto_rawDescOnce sync.Once
	file_map_proto_rawDescData []byte
)

func file_map_proto_rawDescGZIP() []byte {
	file_map_proto_rawDescOnce.Do(func() {
		file_map_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_map_proto_rawDesc), len(file_map_proto_rawDesc)))
	})
	return file_map_proto_rawDescData
}

var file_map_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_map_proto_goTypes = []any{
	(*IdWrapper)(nil),  // 0: example.map.IdWrapper
	(*MapExample)(nil), // 1: example.map.MapExample
	nil,                // 2: example.map.MapExample.IdsEntry
}
var file_map_proto_depIdxs = []int32{
	2, // 0: example.map.MapExample.ids:type_name -> example.map.MapExample.IdsEntry
	0, // 1: example.map.MapExample.IdsEntry.value:type_name -> example.map.IdWrapper
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_map_proto_init() }
func file_map_proto_init() {
	if File_map_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_map_proto_rawDesc), len(file_map_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_map_proto_goTypes,
		DependencyIndexes: file_map_proto_depIdxs,
		MessageInfos:      file_map_proto_msgTypes,
	}.Build()
	File_map_proto = out.File
	file_map_proto_goTypes = nil
	file_map_proto_depIdxs = nil
}
