// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: oneofs.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Results struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*Results_Message
	//	*Results_Id
	Result        isResults_Result `protobuf_oneof:"Result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Results) Reset() {
	*x = Results{}
	mi := &file_oneofs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Results) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Results) ProtoMessage() {}

func (x *Results) ProtoReflect() protoreflect.Message {
	mi := &file_oneofs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Results.ProtoReflect.Descriptor instead.
func (*Results) Descriptor() ([]byte, []int) {
	return file_oneofs_proto_rawDescGZIP(), []int{0}
}

func (x *Results) GetResult() isResults_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Results) GetMessage() string {
	if x != nil {
		if x, ok := x.Result.(*Results_Message); ok {
			return x.Message
		}
	}
	return ""
}

func (x *Results) GetId() uint32 {
	if x != nil {
		if x, ok := x.Result.(*Results_Id); ok {
			return x.Id
		}
	}
	return 0
}

type isResults_Result interface {
	isResults_Result()
}

type Results_Message struct {
	Message string `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

type Results_Id struct {
	Id uint32 `protobuf:"varint,2,opt,name=id,proto3,oneof"`
}

func (*Results_Message) isResults_Result() {}

func (*Results_Id) isResults_Result() {}

var File_oneofs_proto protoreflect.FileDescriptor

const file_oneofs_proto_rawDesc = "" +
	"\n" +
	"\foneofs.proto\x12\x0eexample.oneofs\"A\n" +
	"\aResults\x12\x1a\n" +
	"\amessage\x18\x01 \x01(\tH\x00R\amessage\x12\x10\n" +
	"\x02id\x18\x02 \x01(\rH\x00R\x02idB\b\n" +
	"\x06ResultB\x19Z\x17example.com/proto/protob\x06proto3"

var (
	file_oneofs_proto_rawDescOnce sync.Once
	file_oneofs_proto_rawDescData []byte
)

func file_oneofs_proto_rawDescGZIP() []byte {
	file_oneofs_proto_rawDescOnce.Do(func() {
		file_oneofs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oneofs_proto_rawDesc), len(file_oneofs_proto_rawDesc)))
	})
	return file_oneofs_proto_rawDescData
}

var file_oneofs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_oneofs_proto_goTypes = []any{
	(*Results)(nil), // 0: example.oneofs.Results
}
var file_oneofs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_oneofs_proto_init() }
func file_oneofs_proto_init() {
	if File_oneofs_proto != nil {
		return
	}
	file_oneofs_proto_msgTypes[0].OneofWrappers = []any{
		(*Results_Message)(nil),
		(*Results_Id)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oneofs_proto_rawDesc), len(file_oneofs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oneofs_proto_goTypes,
		DependencyIndexes: file_oneofs_proto_depIdxs,
		MessageInfos:      file_oneofs_proto_msgTypes,
	}.Build()
	File_oneofs_proto = out.File
	file_oneofs_proto_goTypes = nil
	file_oneofs_proto_depIdxs = nil
}
